# we are extending everything from tomcat:8.0 image ...
FROM tomcat:8.0

MAINTAINER jmnmv12
# COPY path-to-your-application-war path-to-webapps-in-docker-tomcat
COPY target/webapp-javaee7-1.1.war /usr/local/tomcat/webapps/